// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN_SCREEN6_H
#define UI_SCREEN_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Screen6
extern void ui_Screen_Screen6_screen_init(void);
extern void ui_Screen_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen_Screen6;
extern lv_obj_t * ui_Screen6_Image_Image6;
extern lv_obj_t * ui_Screen6_Arc_Arc7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

