// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen_Screen3 = NULL;
lv_obj_t * ui_Screen3_Image_Image3 = NULL;
lv_obj_t * ui_Screen3_Arc_Arc4 = NULL;
// event funtions

// build funtions

void ui_Screen_Screen3_screen_init(void)
{
    ui_Screen_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen3_Image_Image3 = lv_img_create(ui_Screen_Screen3);
    lv_img_set_src(ui_Screen3_Image_Image3, &ui_img_children_png);
    lv_obj_set_width(ui_Screen3_Image_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Image_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3_Image_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3_Image_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen3_Image_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen3_Arc_Arc4 = lv_arc_create(ui_Screen_Screen3);
    lv_obj_set_width(ui_Screen3_Arc_Arc4, lv_pct(70));
    lv_obj_set_height(ui_Screen3_Arc_Arc4, lv_pct(70));
    lv_obj_set_align(ui_Screen3_Arc_Arc4, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Screen3_Arc_Arc4, 50);

}

void ui_Screen_Screen3_screen_destroy(void)
{
    if(ui_Screen_Screen3) lv_obj_del(ui_Screen_Screen3);

    // NULL screen variables
    ui_Screen_Screen3 = NULL;
    ui_Screen3_Image_Image3 = NULL;
    ui_Screen3_Arc_Arc4 = NULL;

}
