// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN_SCREEN5_H
#define UI_SCREEN_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Screen5
extern void ui_Screen_Screen5_screen_init(void);
extern void ui_Screen_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen_Screen5;
extern lv_obj_t * ui_Screen5_Image_Image5;
extern lv_obj_t * ui_Screen5_Arc_Arc6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

