// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN_SCREEN2_H
#define UI_SCREEN_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Screen2
extern void ui_Screen_Screen2_screen_init(void);
extern void ui_Screen_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen_Screen2;
extern lv_obj_t * ui_Screen2_Image_Image2;
extern lv_obj_t * ui_Screen2_Arc_Arc3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

