// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include INC_RTOS
#include INC_LOG

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#    error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#    error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

static void timer_cb(lv_timer_t * timer) {
    LV_UNUSED(timer);
    static uint32_t flag = 0;
    lv_arc_set_value(ui_Screen1_Arc_Arc1, flag % 100);
    switch (flag++ % 6) {
        case 0: lv_img_set_src(ui_Screen1_Image_Image1, &ui_img_children_png); break;
        case 1: lv_img_set_src(ui_Screen1_Image_Image1, &ui_img_clean_fill_png); break;
        case 2: lv_img_set_src(ui_Screen1_Image_Image1, &ui_img_cycle_png); break;
        case 3: lv_img_set_src(ui_Screen1_Image_Image1, &ui_img_drop_water_png); break;
        case 4: lv_img_set_src(ui_Screen1_Image_Image1, &ui_img_livephoto_png); break;
        case 5: lv_img_set_src(ui_Screen1_Image_Image1, &ui_img_timer_png); break;
        default: break;
    }
}

void ui_init(void) {
    lv_disp_t *  dispp = lv_disp_get_default();
    lv_theme_t * theme =
        lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE),
                              lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_Screen1_screen_init();
    ui_Startevents____initial_actions0 = lv_obj_create(NULL);
    lv_scr_load_anim(ui_Screen_Screen1, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, false);
    lv_timer_t * t = lv_timer_create(timer_cb, 50, NULL);
}

void ui_destroy(void) {
    ui_Screen_Screen1_screen_destroy();
}
